### ISSUE TITLE
langgraph 0.0.19 version not work

### ISSUE THREAD

**Issue by wulucxy** [bracesproul/langtool-template#2]
langgraph 0.0.19 version not work

```typescript
let finalResult: GraphState | null = null;
  for await (const event of stream) {
    // console.log('\n------\n');
    if (Object.keys(event)[0] === END) {
      console.log('---FINISHED---');
      finalResult = event[END];
    } else {
      console.log('Stream event: ', Object.keys(event)[0]);
    }
  }
```
why the `END` event not fired?

**Comment by bracesproul** [comment]
What exactly is the error you're experiencing? @wulucxy

**Comment by wulucxy** [comment]
the `END` event never fired。But if I switch to v0.0.10, It's all done

**Comment by bracesproul** [comment]
hey @wulucxy thanks for flagging this. I just updated the `finished` branch to the latest versions of LangChain/LangGraph, and updated the code which parses the final result. It should all work as intended now. Thanks!
